version: 1
environment: dev
services:
  portal-backend:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  portal:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  admin:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  rule-control-api:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  engine:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  alert-control-api:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  notifier-runtime:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  stream-control-api:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  ingestion-gateway:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  simlab-api:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  agent-api:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  risk-monitor-api:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  risk-monitor-ui:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  grafana:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  prometheus:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev

  tenant-webhook-receiver:
    image_tag: dev-main
    desired_count: 1
    strategy: rolling
    config_profile: dev
